from sqlalchemy import (
    BigInteger,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    text,
)

from src.core.database.database import Base


class playerHiscoreData(Base):
    __tablename__ = "playerHiscoreData"
    __table_args__ = (
        Index("Unique_player_time", "Player_id", "timestamp", unique=True),
        Index("Unique_player_date", "Player_id", "ts_date", unique=True),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(
        DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    ts_date = Column(Date)
    Player_id = Column(
        ForeignKey("Players.id", ondelete="RESTRICT", onupdate="RESTRICT"),
        nullable=False,
    )
    total = Column(BigInteger)
    attack = Column(Integer)
    defence = Column(Integer)
    strength = Column(Integer)
    hitpoints = Column(Integer)
    ranged = Column(Integer)
    prayer = Column(Integer)
    magic = Column(Integer)
    cooking = Column(Integer)
    woodcutting = Column(Integer)
    fletching = Column(Integer)
    fishing = Column(Integer)
    firemaking = Column(Integer)
    crafting = Column(Integer)
    smithing = Column(Integer)
    mining = Column(Integer)
    herblore = Column(Integer)
    agility = Column(Integer)
    thieving = Column(Integer)
    slayer = Column(Integer)
    farming = Column(Integer)
    runecraft = Column(Integer)
    hunter = Column(Integer)
    construction = Column(Integer)
    league = Column(Integer)
    bounty_hunter_hunter = Column(Integer)
    bounty_hunter_rogue = Column(Integer)
    cs_all = Column(Integer)
    cs_beginner = Column(Integer)
    cs_easy = Column(Integer)
    cs_medium = Column(Integer)
    cs_hard = Column(Integer)
    cs_elite = Column(Integer)
    cs_master = Column(Integer)
    lms_rank = Column(Integer)
    soul_wars_zeal = Column(Integer)
    abyssal_sire = Column(Integer)
    alchemical_hydra = Column(Integer)
    barrows_chests = Column(Integer)
    bryophyta = Column(Integer)
    callisto = Column(Integer)
    cerberus = Column(Integer)
    chambers_of_xeric = Column(Integer)
    chambers_of_xeric_challenge_mode = Column(Integer)
    chaos_elemental = Column(Integer)
    chaos_fanatic = Column(Integer)
    commander_zilyana = Column(Integer)
    corporeal_beast = Column(Integer)
    crazy_archaeologist = Column(Integer)
    dagannoth_prime = Column(Integer)
    dagannoth_rex = Column(Integer)
    dagannoth_supreme = Column(Integer)
    deranged_archaeologist = Column(Integer)
    general_graardor = Column(Integer)
    giant_mole = Column(Integer)
    grotesque_guardians = Column(Integer)
    hespori = Column(Integer)
    kalphite_queen = Column(Integer)
    king_black_dragon = Column(Integer)
    kraken = Column(Integer)
    kreearra = Column(Integer)
    kril_tsutsaroth = Column(Integer)
    mimic = Column(Integer)
    nightmare = Column(Integer)
    nex = Column(Integer)
    phosanis_nightmare = Column(Integer)
    obor = Column(Integer)
    phantom_muspah = Column(Integer)
    sarachnis = Column(Integer)
    scorpia = Column(Integer)
    skotizo = Column(Integer)
    tempoross = Column(Integer)
    the_gauntlet = Column(Integer)
    the_corrupted_gauntlet = Column(Integer)
    theatre_of_blood = Column(Integer)
    theatre_of_blood_hard = Column(Integer)
    thermonuclear_smoke_devil = Column(Integer)
    tombs_of_amascut = Column(Integer)
    tombs_of_amascut_expert = Column(Integer)
    tzkal_zuk = Column(Integer)
    tztok_jad = Column(Integer)
    venenatis = Column(Integer)
    vetion = Column(Integer)
    vorkath = Column(Integer)
    wintertodt = Column(Integer)
    zalcano = Column(Integer)
    zulrah = Column(Integer)

    # New columns added
    rifts_closed = Column(Integer, default=0)
    artio = Column(Integer, default=0)
    calvarion = Column(Integer, default=0)
    duke_sucellus = Column(Integer, default=0)
    spindel = Column(Integer, default=0)
    the_leviathan = Column(Integer, default=0)
    the_whisperer = Column(Integer, default=0)
    vardorvis = Column(Integer, default=0)


class PlayerHiscoreDataLatest(Base):
    __tablename__ = "playerHiscoreDataLatest"

    id = Column(Integer, primary_key=True)
    timestamp = Column(
        DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    ts_date = Column(Date)
    Player_id = Column(
        ForeignKey("Players.id", ondelete="RESTRICT", onupdate="RESTRICT"),
        nullable=False,
        unique=True,
    )
    total = Column(BigInteger)
    attack = Column(Integer)
    defence = Column(Integer)
    strength = Column(Integer)
    hitpoints = Column(Integer)
    ranged = Column(Integer)
    prayer = Column(Integer)
    magic = Column(Integer)
    cooking = Column(Integer)
    woodcutting = Column(Integer)
    fletching = Column(Integer)
    fishing = Column(Integer)
    firemaking = Column(Integer)
    crafting = Column(Integer)
    smithing = Column(Integer)
    mining = Column(Integer)
    herblore = Column(Integer)
    agility = Column(Integer)
    thieving = Column(Integer)
    slayer = Column(Integer)
    farming = Column(Integer)
    runecraft = Column(Integer)
    hunter = Column(Integer)
    construction = Column(Integer)
    league = Column(Integer)
    bounty_hunter_hunter = Column(Integer)
    bounty_hunter_rogue = Column(Integer)
    cs_all = Column(Integer)
    cs_beginner = Column(Integer)
    cs_easy = Column(Integer)
    cs_medium = Column(Integer)
    cs_hard = Column(Integer)
    cs_elite = Column(Integer)
    cs_master = Column(Integer)
    lms_rank = Column(Integer)
    soul_wars_zeal = Column(Integer)
    abyssal_sire = Column(Integer)
    alchemical_hydra = Column(Integer)
    barrows_chests = Column(Integer)
    bryophyta = Column(Integer)
    callisto = Column(Integer)
    cerberus = Column(Integer)
    chambers_of_xeric = Column(Integer)
    chambers_of_xeric_challenge_mode = Column(Integer)
    chaos_elemental = Column(Integer)
    chaos_fanatic = Column(Integer)
    commander_zilyana = Column(Integer)
    corporeal_beast = Column(Integer)
    crazy_archaeologist = Column(Integer)
    dagannoth_prime = Column(Integer)
    dagannoth_rex = Column(Integer)
    dagannoth_supreme = Column(Integer)
    deranged_archaeologist = Column(Integer)
    general_graardor = Column(Integer)
    giant_mole = Column(Integer)
    grotesque_guardians = Column(Integer)
    hespori = Column(Integer)
    kalphite_queen = Column(Integer)
    king_black_dragon = Column(Integer)
    kraken = Column(Integer)
    kreearra = Column(Integer)
    kril_tsutsaroth = Column(Integer)
    mimic = Column(Integer)
    nightmare = Column(Integer)
    nex = Column(Integer)
    phosanis_nightmare = Column(Integer)
    obor = Column(Integer)
    phantom_muspah = Column(Integer)
    sarachnis = Column(Integer)
    scorpia = Column(Integer)
    skotizo = Column(Integer)
    Tempoross = Column(Integer, nullable=False)
    the_gauntlet = Column(Integer)
    the_corrupted_gauntlet = Column(Integer)
    theatre_of_blood = Column(Integer)
    theatre_of_blood_hard = Column(Integer)
    thermonuclear_smoke_devil = Column(Integer)
    tombs_of_amascut = Column(Integer)
    tombs_of_amascut_expert = Column(Integer)
    tzkal_zuk = Column(Integer)
    tztok_jad = Column(Integer)
    venenatis = Column(Integer)
    vetion = Column(Integer)
    vorkath = Column(Integer)
    wintertodt = Column(Integer)
    zalcano = Column(Integer)
    zulrah = Column(Integer)

    # New columns added
    rifts_closed = Column(Integer, default=0)
    artio = Column(Integer, default=0)
    calvarion = Column(Integer, default=0)
    duke_sucellus = Column(Integer, default=0)
    spindel = Column(Integer, default=0)
    the_leviathan = Column(Integer, default=0)
    the_whisperer = Column(Integer, default=0)
    vardorvis = Column(Integer, default=0)


class PlayerHiscoreDataXPChange(Base):
    __tablename__ = "playerHiscoreDataXPChange"

    id = Column(Integer, primary_key=True)
    timestamp = Column(
        DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    ts_date = Column(Date)
    Player_id = Column(
        ForeignKey("Players.id", ondelete="RESTRICT", onupdate="RESTRICT"),
        nullable=False,
        index=True,
    )
    total = Column(BigInteger)
    attack = Column(Integer)
    defence = Column(Integer)
    strength = Column(Integer)
    hitpoints = Column(Integer)
    ranged = Column(Integer)
    prayer = Column(Integer)
    magic = Column(Integer)
    cooking = Column(Integer)
    woodcutting = Column(Integer)
    fletching = Column(Integer)
    fishing = Column(Integer)
    firemaking = Column(Integer)
    crafting = Column(Integer)
    smithing = Column(Integer)
    mining = Column(Integer)
    herblore = Column(Integer)
    agility = Column(Integer)
    thieving = Column(Integer)
    slayer = Column(Integer)
    farming = Column(Integer)
    runecraft = Column(Integer)
    hunter = Column(Integer)
    construction = Column(Integer)
    league = Column(Integer)
    bounty_hunter_hunter = Column(Integer)
    bounty_hunter_rogue = Column(Integer)
    cs_all = Column(Integer)
    cs_beginner = Column(Integer)
    cs_easy = Column(Integer)
    cs_medium = Column(Integer)
    cs_hard = Column(Integer)
    cs_elite = Column(Integer)
    cs_master = Column(Integer)
    lms_rank = Column(Integer)
    soul_wars_zeal = Column(Integer)
    abyssal_sire = Column(Integer)
    alchemical_hydra = Column(Integer)
    barrows_chests = Column(Integer)
    bryophyta = Column(Integer)
    callisto = Column(Integer)
    cerberus = Column(Integer)
    chambers_of_xeric = Column(Integer)
    chambers_of_xeric_challenge_mode = Column(Integer)
    chaos_elemental = Column(Integer)
    chaos_fanatic = Column(Integer)
    commander_zilyana = Column(Integer)
    corporeal_beast = Column(Integer)
    crazy_archaeologist = Column(Integer)
    dagannoth_prime = Column(Integer)
    dagannoth_rex = Column(Integer)
    dagannoth_supreme = Column(Integer)
    deranged_archaeologist = Column(Integer)
    general_graardor = Column(Integer)
    giant_mole = Column(Integer)
    grotesque_guardians = Column(Integer)
    hespori = Column(Integer)
    kalphite_queen = Column(Integer)
    king_black_dragon = Column(Integer)
    kraken = Column(Integer)
    kreearra = Column(Integer)
    kril_tsutsaroth = Column(Integer)
    mimic = Column(Integer)
    nightmare = Column(Integer)
    nex = Column(Integer)
    obor = Column(Integer)
    phantom_muspah = Column(Integer)
    phosanis_nightmare = Column(Integer)
    sarachnis = Column(Integer)
    scorpia = Column(Integer)
    skotizo = Column(Integer)
    Tempoross = Column(Integer, nullable=False)
    the_gauntlet = Column(Integer)
    the_corrupted_gauntlet = Column(Integer)
    theatre_of_blood = Column(Integer)
    theatre_of_blood_hard = Column(Integer)
    thermonuclear_smoke_devil = Column(Integer)
    tombs_of_amascut = Column(Integer)
    tombs_of_amascut_expert = Column(Integer)
    tzkal_zuk = Column(Integer)
    tztok_jad = Column(Integer)
    venenatis = Column(Integer)
    vetion = Column(Integer)
    vorkath = Column(Integer)
    wintertodt = Column(Integer)
    zalcano = Column(Integer)
    zulrah = Column(Integer)
    # New columns added
    rifts_closed = Column(Integer, default=0)
    artio = Column(Integer, default=0)
    calvarion = Column(Integer, default=0)
    duke_sucellus = Column(Integer, default=0)
    spindel = Column(Integer, default=0)
    the_leviathan = Column(Integer, default=0)
    the_whisperer = Column(Integer, default=0)
    vardorvis = Column(Integer, default=0)
